name: Pylint

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy
        pip install opencv-python
        pip install pillow
        pip install tensorflow
        pip install scikit-learn
    - name: Running the code
      run: |
        python create_datasets.py
        python create_models.py
